version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: price_tracker
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_PASSWORD

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
      - mysql-data:/var/lib/mysql  # <-- data persistence
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_HOST: localhost

volumes:  # <-- Data persistence volume
  mysql-data: